### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by daankortenbach** [trzy/llava-cpp-server#5]
Ran this overnight as a test to describe ~3000 images. llava-server grew to +16GB memory resulting in massive swap space used. About 1750 images processed at the point I restarted it to free up some memory. Not sure if intended or a bug. Seams much as my script calls the API so should not build up like that.

System: Mac Mini M1 16GB

It did the work anyway but I want to do +500000 images... I could just restart the server every 500 images or so but I'd rather have it running continuously as it will take a looooooong time.

**Comment by trzy** [comment]
Almost certainly a bug but the question is where? I free everything I malloc, so it's likely either a bug in the underlying llama.cpp code or because I'm misusing their functions.

I haven't built this project in a while because llama.cpp now supports llava with its server. You could perhaps try updating the submodule to see if it still builds and has this problem fixed. If not, I would also recommend llama.cpp (run the "server" binary that is produced). For an example of how to call their endpoint: https://github.com/trzy/multimodal-cloud-tests/blob/main/llava-cpp-test.py

**Comment by daankortenbach** [comment]
Second try it went over 24GB. Def not an option for half a million of images lol. It would also take +100 days on my M1 so I was already looking into Runpod. So thank you for the link to your llava-cpp-test.py script. I'm still learning python (after 20 years of php web development) and this helps a lot.
